export const offerData = {
    image: "assets/gift_icon.png",
    tittle: "CHOOSE FROM",
    tittle2: "Hundreds of Live Offers",
    CenterTextTittle: "Can’t find the offer you were looking for? Don’t worry, we got you!",
    CenterTextQuotes: 'vCommission offers',
    CenterTextStrong: "tens of thousands of affiliate program",
    centerTextDescription: 'that align with your business goals and requirements. So,  if you cannot fiparticular offefret not we can activate it for you at any given time. All you need to do is help us out by fillingthe below-mentioned form following which, we will add the particular offer at your request',
    CenterBtn: "SUBMIT OFFER DETAILS",

    offerDataLoop: [
        {
            CardHeading: "Myntra.com CPS - India",
            CardImage: "assets/Myntra_logo.png",
            CardParagraph: "Offer ID:",
            CardStrong: "22",
            CardParagraph2: "Payout:",
            CardStrong2: "5.92 %",
            CardParagraph3: "Expiration:",
            CardStrong3: "31-Dec-2021",
            CardButton: "Join",
        },
        {
            CardHeading: "Makemytrip.com Domestic  - India",
            CardImage: "assets/MMT_Logo_100x50.png",
            CardParagraph: "Offer ID:",
            CardStrong: "44",
            CardParagraph2: "Payout:",
            CardStrong2: "105.00",
            CardParagraph3: "Expiration:",
            CardStrong3: "31-Dec-2021",
            CardButton: "Join",
        },
        {
            CardHeading: "Zivame.com CPS - India",
            CardImage: "assets/zivame_logo (1).png",
            CardParagraph: "Offer ID:",
            CardStrong: "100",
            CardParagraph2: "Payout:",
            CardStrong2: "11.90 %",
            CardParagraph3: "Expiration:",
            CardStrong3: "31-Dec-2021",
            CardButton: "Join",
        },
        {
            CardHeading: "Floweraura.com CPS - India",
            CardImage: "assets/Floweraura.png",
            CardParagraph: "Offer ID:",
            CardStrong: "787",
            CardParagraph2: "Payout:",
            CardStrong2: "7.00 %",
            CardParagraph3: "Expiration:",
            CardStrong3: "31-Dec-2021",
            CardButton: "Join",
        },
        {
            CardHeading: "MakeMyTrip.com Bus CPS - India",
            CardImage: "assets/MMT Logo_100x50.png",
            CardParagraph: "Offer ID:",
            CardStrong: "1030",
            CardParagraph2: "Payout:",
            CardStrong2: "35.00",
            CardParagraph3: "Expiration:",
            CardStrong3: "31-Dec-2021",
            CardButton: "Join",
        },
        {
            CardHeading: "OYOrooms.com CPS - India",
            CardImage: "assets/Oyo_logo.png",
            CardParagraph: "Offer ID:",
            CardStrong: "1362",
            CardParagraph2: "Payout:",
            CardStrong2: "3.50 %",
            CardParagraph3: "Expiration:",
            CardStrong3: "31-Dec-2021",
            CardButton: "Join",
        },
    ]
}

