export const faqData = {
    pagename:"FAQ",
    tittle1:"TO KNOW",
    tittle2:"BEFORE YOU GET",
    greentittle1:" ASSOCIATED",
    greentittle2:" WITH US",
    description:"Here are some questions we often get asked. If you have a question of your own please email us.",
    // question1tittle:"What is vCommission",
    // questionimg:"assets/sm_5afbe35fd36cc.jpg",
    // question2tittle:"What are the requirements for becoming a vCommission publisher?",
    // question3tittle:"When did vCommission come into existence?",
    // question4tittle:"How long does it take for an application to be approved?",
    // question5tittle:"What is the cost to join vCommission?",
    // question6tittle:"When do I get paid?",
    // question7tittle:"Do I need to submit any documents?",
    // question8tittle:"Is there a minimum that I have to earn in order to get paid?",
    faqimg:"assets/faq_img-1536x602.jpg",
    pagination:"Previous Next",
    copyscapeimg:"assets/copyscape-banner-white-200x25-1.png"
}